name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          user: IndoNLP
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          plugin_introduction: yes
          plugin_stargazers: yes
          plugin_contributors: yes
          plugin_contributors_contributions: yes
          config_timezone: Asia/Indonesia
          config_order: base.header, introduction, contributors, stargazers
