name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          user: IndoNLP
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, community, repositories
          plugin_introduction: yes
          plugin_people: yes
          plugin_people_types: members
          plugin_people_shuffle: yes
          plugin_achievements: yes
          plugin_achievements_ignored: polyglots, member, organization
          plugin_followup: yes
          plugin_followup_archived: no
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: issue, pr, release, fork, review, ref/create, public, member
          config_timezone: Asia/Jakarta
          config_order: base.header, base.community, base.repositories, introduction, activity, achievements, followup
