name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          user: IndoNLP
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, community, repositories
          plugin_traffic: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no
          plugin_introduction: yes
          plugin_people: yes
          plugin_people_types: members
          plugin_people_shuffle: yes
          plugin_stargazers: yes
          plugin_achievements_display: compact
          plugin_achievements: yes
          plugin_achievements_ignored: polyglots, member, organization
          plugin_followup: yes
          plugin_followup_archived: no
          plugin_activity: yes
          plugin_activity_limit: 3
          plugin_activity_days: 7
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          config_timezone: Asia/Jakarta
          config_order: base, introduction, traffic, habits, people, followup, achievements, stargazers, activity
