name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          user: IndoNLP
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_traffic: yes
          plugin_introduction: yes
          plugin_stargazers: yes
          plugin_achievements: yes
          plugin_achievements_only: inspirer, developer, maintainer
          config_timezone: Asia/Jakarta
